version: "3"

services:
  postgres:
    image: postgres:12
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    networks:
      - postgres-network

  api:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - postgres
    command: "sh entrypoint.sh"
    networks:
      - postgres-network


networks:
  postgres-network:

volumes:
  postgres-data:
